### ISSUE TITLE
Some users in the UK are experiencing an issue connecting to the pool using port 4444

### ISSUE THREAD

**Issue by fullyautomatedthings** [Cricket-Miner/CricketMiner-Issues#3]
Users in the UK cannot connect over port 4444 or the backup port 14444. Back up port 80 will be added.

**Comment by Cricket-Miner** [comment]
Currently researching user friendly pool that allows for both port 80 support and low minimum payout settings.

**Comment by Cricket-Miner** [comment]
Several additional pools have been added. Pools will be available in beta but have been contacted to allow support for general release. Pools may be removed if support is not granted.
